### PR TITLE
Add zalando org to zappr

### PR DESCRIPTION
**Pull request by prayerslayer**

### CODE REVIEW

**Comment by prayerslayer** [comment]
👍

**Comment by mfellner** [comment]
👍

**Comment by mfellner** [comment]
👍

**Comment by mfellner** [comment]
👍

**Comment by mfellner** [comment]
👍

**Comment by mfellner** [comment]
👍

**Comment by mfellner** [comment]
👍

**Comment by mfellner** [comment]
👍

**Comment by spaudanjo** [comment]
U miss one? Here u go 👍

**Comment by spaudanjo** [comment]
👍

**Comment by prayerslayer** [comment]
test

**Pull request closed without merging**
